languageCode = "en-us"
title = "Dev Log"
baseURL = "localhost:1313"
googleanalytics = ""
disqusShortname = "ahnsv"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"
[languages.ko]
  languageName = "Korean"
  title = "데브 로그"
theme = "curttimson"
