languageCode = "en-us"
title = "Dev Log"
baseURL = "http://localhost:1313/"
googleanalytics = ""
disqusShortname = "ahnsv"



[languages]
[languages.en]
  languageName = "English"
[languages.ko]
  languageName = "Korean"
  title = "데브 로그"
theme = "curttimson"
